version: "3.8"

services:
  es-master01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es-master01
    environment:
      - node.name=es-master01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - discovery.seed_hosts=es-master02,es-master03,es-data01,es-data02,es-data03
      - node.roles=[ master ]
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esmasterdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic-net

  es-master02:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es-master02
    environment:
      - node.name=es-master02
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - discovery.seed_hosts=es-master01,es-master03,es-data01,es-data02,es-data03
      - node.roles=[ master ]
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esmasterdata02:/usr/share/elasticsearch/data
    networks:
      - elastic-net

  es-master03:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es-master03
    environment:
      - node.name=es-master03
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - discovery.seed_hosts=es-master01,es-master02,es-data01,es-data02,es-data03
      - node.roles=[ master ]
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esmasterdata03:/usr/share/elasticsearch/data
    networks:
      - elastic-net

  es-data01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es-data01
    environment:
      - node.name=es-data01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - discovery.seed_hosts=es-master01,es-master02,es-master03,es-data02,es-data03
      - node.roles=[ data ]
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    networks:
      - elastic-net

  es-data02:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es-data02
    environment:
      - node.name=es-data02
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - discovery.seed_hosts=es-master01,es-master02,es-master03,es-data01,es-data03
      - node.roles=[ data ]
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - elastic-net

  es-data03:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es-data03
    environment:
      - node.name=es-data03
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es-master01,es-master02,es-master03
      - discovery.seed_hosts=es-master01,es-master02,es-master03,es-data01,es-data02
      - node.roles=[ data ]
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata03:/usr/share/elasticsearch/data
    networks:
      - elastic-net

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    depends_on:
      - es-master01
      - es-master02
      - es-master03
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es-master01:9200
    volumes:
      - kibanadata:/usr/share/kibana/data
    networks:
      - elastic-net

volumes:
  esmasterdata01:
    driver: local
  esmasterdata02:
    driver: local
  esmasterdata03:
    driver: local
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local
  kibanadata:
    driver: local

networks:
  elastic-net:
    driver: bridge